### ISSUE TITLE
Click on point entity shows choropleth popup

### ISSUE THREAD

**Issue by nesnoj** [empowerplan/epp-app#10]
When choropleth is active, clicking on a power unit (or other point entity) always shows the choropleth popup.
Both objects' popups should be accessible, depending on what is clicked on.

![image](https://github.com/empowerplan/epp-app/assets/15910173/e2c67b34-02d3-4127-b353-72ee8920370b)

**Comment by nesnoj** [comment]
depends on #12

**Comment by henhuy** [comment]
> Solved in [rl-institut/digiplan#393](https://github.com/rl-institut/digiplan/pull/393) , I'll integrate here

This is actually a different bug - showing an empty popup.
-> point popup depends on order of Popups - but luckily I fixed this in #12 
So merging it solves two problems

**Comment by henhuy** [comment]
> Nevertheless, #393 must still be implemented here

In fact, this is also covered by updating mapeninge...

**Comment by henhuy** [comment]
> In fact, this is also covered by updating mapeninge...

This is not true. Fixed it in newest mapengine version v0.18.3.
Add PR for this issue
