### ISSUE TITLE
Distinguish between aggregated components and single components on map

### ISSUE THREAD

**Issue by nesnoj** [empowerplan/epp-app#11]
Tests with users have shown that this feature is very helpful.
Original discussion: https://github.com/rl-institut/digiplan/issues/227

Also, the attribute "Anlagenanzahl" should be emphasized and shown first in the popup's list.

![image](https://github.com/empowerplan/epp-app/assets/15910173/b830b14e-771a-42b8-b6b6-14090de486d1)

**Comment by nesnoj** [comment]
Any updates here? Maybe a task for @josihoppe ?

**Comment by henhuy** [comment]
Started a draft to implement this.
Did we want to diff between `geometry_approximated` comps as well?
Or just the aggregated ones?

**Comment by nesnoj** [comment]
> Started a draft to implement this. Did we want to diff between `geometry_approximated` comps as well? Or just the aggregated ones?

Thx for tackling this!
It's sufficient to show the different symbol for agg. units. As 99% of units where `geometry_approximated=true` are agg. ones this would not create much additional value.
