### ISSUE TITLE
Implement scenario settings

### ISSUE THREAD

**Issue by henhuy** [empowerplan/epp-app#21]
Right now the user can select a scenario at the third menu step.
In my understanding, selecting a scenario will preset the controls for the next menu.

Regarding this approach, I have one question @nesnoj :
What happens if user selects a scenario and changes a slider in the next menu afterwards?
Does a new scenario "Custom settings" appear when going back to scenario menu?
Or are the sliders and switches are disabled if a predefined scenario is selected? (I think not, right?)

TODOS:
- [ ] prepare a folder containing config files for each scenario
- [x] adapt controls from config file if user selects a scenario (maybe, a certain order has to be preserved, as slider ranges depend on detail settings)
- [ ] ? select "custom scenario" if user changes sliders/switches? (see question above)

**Comment by nesnoj** [comment]
I'll check this out next week
