### ISSUE TITLE
Show 2 layers on settings change

### ISSUE THREAD

**Issue by nesnoj** [empowerplan/epp-app#28]
In #25 new controls for wind are being implemented.
For step 3 (2027+) two layers are to be shown on the map a the same time:
- wind areas from step 2 (foreground)
- entire region (bkg_vg250_region, background) as hatched/shaded area to implicate that additional areas could be anywhere.

Is this simple to implement, just load 2 layers instead of 1 (as now)?

**Comment by nesnoj** [comment]
Ah, we had that already in the PV ground settings, nevermind.
But can you make it hatched and maybe 50% opaque or so?

**Comment by henhuy** [comment]
For sure!
