### ISSUE TITLE
Provide more info for static (non-choropleth) layers

### ISSUE THREAD

**Issue by nesnoj** [empowerplan/epp-app#29]
Is it possible to provide more info on (non-choropleth) map layers when hovering? Like this:
![image](https://github.com/empowerplan/epp-app/assets/15910173/460eb31e-9605-4a7c-9007-20dee20b2ad2)

That'd be helpful for the layers shown in settings.
(Alternatively, the bottom-right legend could show this info when layer is active or on hover..)

**Comment by henhuy** [comment]
Both should be possible!
