### ISSUE TITLE
Calculate key results for detail settings

### ISSUE THREAD

**Issue by nesnoj** [empowerplan/epp-app#52]
Calculate key numbers in detail panel, they should change on slider change:

![image](https://github.com/empowerplan/epp-app/assets/15910173/c043b53d-5261-459d-bbb2-e3faf725ae55)

Calculation is quite similar to main slider calculation.
You'll need the new `technology_data.json` from the Wolke.

Wind
1. area in ha
2. area * power_density / nominal_power_per_unit (`technology_data.json` -> `nominal_power_per_unit` -> `wind`)
3. area * power_density * full_load_hours (2045)

PV ground
1. area in ha
2. area * power_density * full_load_hours (2045)
with power_density and full_load_hours per technology:
_soil_quality_low_: `power_density` -> `pv_ground`, `full_load_hours` -> `pv_ground`
_soil_quality_medium_: `power_density` -> `pv_ground_vertical_bifacial`, `full_load_hours` -> `pv_ground_vertical_bifacial`
_permanent crops_: `power_density` -> `pv_ground_elevated`, `full_load_hours` -> `pv_ground_elevated`

PV roof
1. area in ha
2. area * power_density * full_load_hours (2045)

(All values rounded to int)

**Comment by henhuy** [comment]
Waits for https://github.com/IonDen/ion.rangeSlider/issues/792
If it cannot wait, I will implement it using AJAX instead of HTMX
