### ISSUE TITLE
Duplicated layers - couple button/layer state

### ISSUE THREAD

**Issue by nesnoj** [empowerplan/epp-app#56]
New layers have been integrated in #47 . Some are duplicated in different sections by intention, e.g. settlements.
When you switch on both settlement layers and then deactivate one of them, the layer hides but the 2nd button remains active. Their state should be coupled.
Is there an easy solution without hardcoding behaviour of each and every switch?

**Comment by henhuy** [comment]
I think I could listen to trigger event and turn on/off related switches as well.
I'll check

**Comment by henhuy** [comment]
As far as I can see, all layers from negative criteria section have to be coupled, except the following:
- Flächennaturdenkmale
- Vorzug klimarobustes Ackerland
- Vorzug Dauerkultur
- Vorzug Grünland
which have no "partner" in other sections, am I right?
Will implement coupling now.
