### ISSUE TITLE
The navigation buttons should have different states

### ISSUE THREAD

**Issue by bmlancien** [empowerplan/epp-app#6]
- Step 1: no "previous" button
- Steps 2, 3, 4: both buttons visible
- Step 5: no "next" button
- "Previous" button without background color
- "Next" button with blue background OR disabled in some cases

**Comment by nesnoj** [comment]
Yes, please :+1:

**Comment by bmlancien** [comment]
As mentioned @henhuy, can you hide the "previous" button on step 1 and "next" button on step 5? In order to be sure that it doesn't break the layout, use `visibility: hidden` instead of `display: none`, although it should also work. Thanks!

**Comment by henhuy** [comment]
Done in current dev
