### ISSUE TITLE
Indicate running optimization in result elements

### ISSUE THREAD

**Issue by nesnoj** [empowerplan/epp-app#60]
As the optimization will take some time, split result into 2 steps:
5. "Ergebnisse" (instant results) - results which can be calculated without esys optimization (area usage, production, consumption). Optimization for 2. should start when this step is viewed.
6. "Detailergebnisse" (optimized esys results) - needs 1-4 min to be calculated

So we'd have 6 steps, which is quite a lot. Alternatively, instead of adding an additional one, the detailed results could be made available somewhere in the 5th step?

**Comment by bmlancien** [comment]
5 steps is better, but 6 steps is okay, I guess. 
In my opinion, having the detailed results as an extra step is better if we think these results is something the users should see. Keeping them in step 5 would mean that the detailed results are something optional, which is also fine. It depends what we want the users to do and see.

**Comment by henhuy** [comment]
I thought of some results beeing disabled at first, which are getting enabled once the simulation has finished

**Comment by nesnoj** [comment]
> I thought of some results beeing disabled at first, which are getting enabled once the simulation has finished

Good idea, that's a viable option we already used in the 1st stemp tool. In this case every result element needed some spinner or similar and dummy, symbolic content. Could you implement this functionality @henhuy ?
