### ISSUE TITLE
Tooltip texts from layer legend are sometimes truncated

### ISSUE THREAD

**Issue by bmlancien** [empowerplan/epp-app#88]
The tooltip texts are sometimes truncated on top if the info icon is at the top of the screen. It is also slightly truncated on the right side. Therefore the texts should be moved down and to the left.

**Comment by nesnoj** [comment]
Yes, please fix :)
Also, the text should be left-aligned and I'd like to add line breaks - is this easily possible?

![image](https://github.com/empowerplan/epp-app/assets/15910173/3914b8ae-acc8-41d8-ad1c-684ffb13cd6c)
